name: Pylint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        # Flask is added due to pipeline artifact, better than modify the actual code to make the CI work.
        pip install pylint sphinx flask
        # Original Github way of installing dependencies
        # python -m pip install --upgrade pip
        cd ./python
        python setup.py install
    - name: Analysing the code with pylint
      run: |
        pylint `ls -R|grep .py$|xargs`
